---
snapshot:
  max_age: 1800

keystore:
  - "ConsulKeystore"
  - host: localhost
    port: 8500

lockagent:
  - "ConsulLockAgent"
  - host: localhost
    port: 8500

backend:
  - "MySQLBackend"
  - host: localhost
    loadbalancer:
      host:
