---
drivers:
  'snappy.backend.mysql':
    host: localhost
    user: admin
    password: '1234567890'
  'snappy.snapshot.zfs':
    filesystem: 'data/mysql'

snapshot:
  max_age: 1800

keystore:
  - "ConsulKeystore"
  - host: 10.32.25.161
    port: 8500

lockagent:
  - "ConsulLockAgent"
  - host: 10.32.25.161
    port: 8500
